sqlite3 auctions.db < create.sql
sqlite3 auctions.db < load.txt
sqlite3 auctions.db < constraints_verify.sql
sqlite3 auctions.db < trigger1_add.sql
sqlite3 auctions.db < trigger2_add.sql
sqlite3 auctions.db < trigger3_add.sql
sqlite3 auctions.db < trigger4_add.sql
sqlite3 auctions.db < trigger5_add.sql
sqlite3 auctions.db < trigger6_add.sql
sqlite3 auctions.db < trigger7_add.sql
sqlite3 auctions.db < trigger8_add.sql
