DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Bids;
DROP TABLE IF EXISTS CategoryList;

CREATE TABLE Items(
	ItemID INTEGER PRIMARY KEY,
	SellerID TEXT NOT NULL,
	Name TEXT NOT NULL,
	Currently REAL,
	Buy_Price REAL,
	First_Bid REAL NOT NULL,
	Number_of_Bids INTEGER,
	Started DATETIME,
	Ends DATETIME CHECK (Ends > Started),
	Description TEXT,
	FOREIGN KEY(SellerID) REFERENCES User(UserID)
);

CREATE TABLE Users(
	UserID TEXT PRIMARY KEY,
	Rating INTEGER,
	Location TEXT,
	Country TEXT
);

CREATE TABLE Category(
	ItemID INTEGER NOT NULL,
	Category TEXT NOT NULL,
	CONSTRAINT unique_item_category UNIQUE (ItemID, Category),
	FOREIGN KEY (Category) REFERENCES CategoryList(Category),
	FOREIGN KEY (ItemID) REFERENCES Item(ItemID)
);
CREATE TABLE Bids(
	UserID TEXT NOT NULL,
	ItemID INTEGER NOT NULL,
	Time DATETIME NOT NULL,
	Amount REAL NOT NULL,
	FOREIGN KEY (UserID) REFERENCES User(UserID),
	FOREIGN KEY (ItemID) REFERENCES Item(ItemID)
);
CREATE TABLE CategoryList(
	Category TEXT PRIMARY KEY
);
